#pragma once


#define ERROR_SUCCESS 					0

#define ERROR_ST_SET_EPOLL 				100
#define ERROR_ST_INITIALIZE 				101
#define ERROR_ST_OPEN_SOCKET				102
#define ERROR_ST_CREATE_LISTEN_THREAD			103
#define ERROR_ST_CREATE_CYCLE_THREAD			104

#define ERROR_SOCKET_CREATE 				200
#define ERROR_SOCKET_SETREUSE 				201
#define ERROR_SOCKET_BIND 				202
#define ERROR_SOCKET_LISTEN 				203
#define ERROR_SOCKET_CLOSED 				204
#define ERROR_SOCKET_GET_PEER_NAME			205
#define ERROR_SOCKET_GET_PEER_IP			206
#define ERROR_SOCKET_READ				207
#define ERROR_SOCKET_READ_FULLY				208
#define ERROR_SOCKET_WRITE				209
#define ERROR_SOCKET_WAIT				210
#define ERROR_SOCKET_TIMEOUT				211